"""P1: keywords articles internal_links tables

Revision ID: 7c9ebd781226
Revises: 71cab8c35576
Create Date: 2026-08-24 14:25:38.599080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9ebd781226'
down_revision: Union[str, None] = '71cab8c35576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('search_engine', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_user_id'), 'keywords', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seo_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_detected_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seo_detail', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_articles_keyword_id'), 'articles', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('ix_articles_user_id'), 'articles', ['user_id'], unique=False)
    op.create_table('internal_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=False),
    sa.Column('target_article_id', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.String(length=200), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_links_source_article_id'), 'internal_links', ['source_article_id'], unique=False)
    op.create_index(op.f('ix_internal_links_target_article_id'), 'internal_links', ['target_article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_links_target_article_id'), table_name='internal_links')
    op.drop_index(op.f('ix_internal_links_source_article_id'), table_name='internal_links')
    op.drop_table('internal_links')
    op.drop_index(op.f('ix_articles_user_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_keyword_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_keywords_user_id'), table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
